#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Rodando lint-staged..."
npx lint-staged

echo "🧪 Rodando testes afetados..."
npx ng test --watch=false --browsers=ChromeHeadless --include='**/*.spec.ts'
